j100_0897/manipulators:
  controller_manager:
    ros__parameters:
      update_rate: 1000
      joint_state_broadcaster:
        type: 'joint_state_broadcaster/JointStateBroadcaster'
      arm_0_joint_trajectory_controller:
        type: 'joint_trajectory_controller/JointTrajectoryController'
      arm_0_gripper_controller:
        type: 'position_controllers/GripperActionController'
  arm_0_joint_trajectory_controller:
    ros__parameters:
      joints: ['arm_0_joint_1', 'arm_0_joint_2', 'arm_0_joint_3', 'arm_0_joint_4', 'arm_0_joint_5', 'arm_0_joint_6']
      command_interfaces: ['position']
      state_interfaces: ['position', 'velocity']
      state_publish_rate: 100.0
      action_monitor_rate: 20.0
      allow_partial_joints_goal: False
      constraints:
        stopped_velocity_tolerance: 0.0
        goal_time: 0.0
  arm_0_gripper_controller:
    ros__parameters:
      default: True
      joint: 'arm_0_gripper_right_finger_bottom_joint'
      allow_stalling: True
